services:
  - type: web
    name: sellytics-ai-agent
    env: docker
    repo: https://github.com/Zanarepo/AIAgent
    branch: main
    dockerCommand: gunicorn -w 4 -b 0.0.0.0:$PORT api:app
    envVars:
      - key: SUPABASE_URL
        value: https://qffcyvjugmtojpdgqriv.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 8000