services:
  - type: web
    name: sellytics-ai-agent
    env: python
    repo: https://github.com/Zanarepo/AIAgent
    branch: main
    pythonVersion: 3.9.18  # Match working setup
    buildCommand: pip install setuptools && pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT api:app
    envVars:
      - key: SUPABASE_URL
        value: https://qffcyvjugmtojpdgqriv.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: PORT
        value: 8000